# XDG STANDARD (Corregido el uso de $HOME en lugar de ~)
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share" # Es más común usar .local/share para XDG_DATA_HOME
export XDG_CACHE_HOME="$HOME/.cache"     # XDG_CACHE_HOME debe estar en $HOME/.cache
export XDG_STATE_HOME="$HOME/.local/state" # XDG_STATE_HOME es $HOME/.local/state

# ZSH GLOBAL VARS
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/.zcachecompdump-${SHORT_HOST}-${ZSH_VERSION}"


export PS1="%{%F{226}%}%n%{%F{220}%}@%{%F{214}%}%m %{%F{33}%}%1~ %{%f%}$ "
export RPROMPT="%D %T"

export STARSHIP_CONFIG="/etc/starship.toml"


source /etc/zsh/zaliases
source /etc/zsh/zprofile
source /etc/zsh/zoptions
source /etc/zsh/zfunctions
